version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-temp
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 100
      runas: ubuntu
  ValidateService:
    - location: scripts/reloadServer.sh
      timeout: 100
      runas: ubuntu