version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: "12"
  build:
    commands:
    - npm i
    - aws cloudformation package --template-file template.yml --s3-bucket device-status-artifact
      --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
  - template.yml
  - outputtemplate.yml
